package dev.favourdevlabs.cleanthes.security

import android.net.Uri

/**
 * Parses otpauth:// URIs generated by services during 2FA setup.
 *
 * Full URI format:
 *   otpauth://totp/ISSUER:ACCOUNT?secret=BASE32&issuer=ISSUER&algorithm=SHA1&digits=6&period=30
 *
 * All parameters except 'secret' are optional and have sensible defaults.
 */
object OtpAuthParser {

    data class OtpAuthData(
        val secret: String,       // Base32 shared secret — the critical field
        val issuer: String?,      // e.g. "GitHub", "Google"
        val accountName: String?, // e.g. "pepe@example.com"
        val algorithm: String,    // "SHA1", "SHA256", or "SHA512"
        val digits: Int,          // almost always 6
        val period: Int           // almost always 30
    )

    /**
     * @throws IllegalArgumentException if the URI is not a valid otpauth:// URI
     *                                  or if the secret parameter is missing.
     * @throws UnsupportedOperationException if the URI is HOTP (counter-based).
     */
    @Throws(IllegalArgumentException::class, UnsupportedOperationException::class)
    fun parse(rawUri: String): OtpAuthData {
        val uri = Uri.parse(rawUri.trim())

        if (!"otpauth".equals(uri.scheme, ignoreCase = true))
            throw IllegalArgumentException("Not an otpauth URI. Got scheme: ${uri.scheme}")

        val type = uri.host
        if ("hotp".equals(type, ignoreCase = true))
            throw UnsupportedOperationException("HOTP (counter-based) is not supported — only TOTP.")
        if (!"totp".equals(type, ignoreCase = true))
            throw IllegalArgumentException("Unknown OTP type: $type")

        // --- secret (required) ---
        var secret = uri.getQueryParameter("secret")
            ?.takeIf { it.trim().isNotEmpty() }
            ?: throw IllegalArgumentException("Missing required 'secret' parameter.")
        secret = secret.uppercase().replace(Regex("[=\\s]"), "")

        // Validate it's actually valid Base32 by attempting a decode
        try {
            TOTPGenerator.decodeBase32(secret)
        } catch (e: IllegalArgumentException) {
            throw IllegalArgumentException("Secret is not valid Base32: ${e.message}")
        }

        // --- issuer and account from path ---
        var issuer: String?      = null
        var accountName: String? = null
        val path = uri.path
        if (path != null && path.length > 1) {
            val label = Uri.decode(path.substring(1))
            if (label.contains(":")) {
                val parts = label.split(":", limit = 2)
                issuer      = parts[0].trim()
                accountName = parts[1].trim()
            } else {
                accountName = label.trim()
            }
        }

        // Query parameter 'issuer' takes precedence over the path-derived one
        uri.getQueryParameter("issuer")?.trim()?.takeIf { it.isNotEmpty() }?.let {
            issuer = it
        }

        // --- algorithm (default SHA1) ---
        val algorithm = uri.getQueryParameter("algorithm")
            ?.trim()
            ?.uppercase()
            ?.takeIf { it == "SHA256" || it == "SHA512" }
            ?: "SHA1"

        // --- digits (default 6) ---
        val digits = uri.getQueryParameter("digits")?.trim()?.toIntOrNull()
            ?.takeIf { it == 6 || it == 7 || it == 8 } ?: 6

        // --- period (default 30) ---
        val period = uri.getQueryParameter("period")?.trim()?.toIntOrNull()
            ?.takeIf { it > 0 } ?: 30

        return OtpAuthData(secret, issuer, accountName, algorithm, digits, period)
    }
}
